import React,{useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,Globe2,Crosshair,Users,Shield,Database,ExternalLink} from 'lucide-react';
import SpotlightCard from './components/SpotlightCard';
import CountUp from './components/CountUp';
import BlurText from './components/BlurText';
import Aurora from './components/Aurora';
import './styles.css';
const metrics=[['INCIDENTS',64508,Activity],['FATALITIES',188427,Crosshair],['INJURIES',125789,Shield],['HOSTAGES / MISSING',32761,Users]];
const nav=['Overview','Geography','Tactics','Actors','Casualties'];
function DashboardFrame(){const frame=useRef(null);useEffect(()=>{const f=frame.current;const onLoad=()=>{try{const doc=f.contentDocument;const style=doc.createElement('style');style.textContent='html,body{background:transparent!important;color:#d9e5f2!important;padding:0!important}h1,p.sub,.note,.footer{display:none!important}body{font-family:Inter,system-ui,sans-serif!important}.section{background:rgba(9,16,29,.55)!important;border:1px solid rgba(150,190,220,.12)!important;box-shadow:0 20px 70px rgba(0,0,0,.22)!important;border-radius:18px!important;max-width:none!important;padding:16px!important;margin:0 0 16px!important;backdrop-filter:blur(18px)!important}.row{gap:16px!important;margin-top:0!important}.row>div{min-width:320px!important}.kpis{display:none!important}.plot-container,.js-plotly-plot{border-radius:12px!important;overflow:hidden!important}.modebar{opacity:.2!important}';doc.head.appendChild(style)}catch(e){console.warn('Dashboard frame styling unavailable',e)}};f?.addEventListener('load',onLoad);return()=>f?.removeEventListener('load',onLoad)},[]);return <iframe ref={frame} className="dashboard-frame" title="GRID analytical visualizations" src="/grid_terrorism_dashboard.html"/>}
function App(){const[active,setActive]=React.useState('Overview');const jump=name=>{setActive(name);document.getElementById(name.toLowerCase())?.scrollIntoView({behavior:'smooth',block:'start'})};return <main><Aurora/><div className="grain"/><header className="topbar glass"><div className="brand"><div className="brand-mark">N01</div><div><strong>GLOBAL INCIDENT INTELLIGENCE</strong><span>GTTAC / GRID ANALYTICS</span></div></div><div className="status"><span className="pulse"/>LIVE DATA SNAPSHOT <b>2018–2026</b></div></header><section className="hero" id="overview"><div className="eyebrow"><Database size={14}/> RECORD OF INCIDENT DATABASE</div><h1><BlurText>Global Incident Intelligence</BlurText></h1><p>Statistical, geographic and actor-level analysis of the supplied GTTAC GRID snapshot.</p><div className="hero-line"/></section><nav className="nav glass" aria-label="Dashboard sections">{nav.map((n,i)=><button key={n} className={active===n?'active':''} onClick={()=>jump(n)}><span>0{i+1}</span>{n}</button>)}</nav><section className="metrics">{metrics.map(([label,value,Icon])=><SpotlightCard className="metric glass" key={label}><Icon size={17}/><span className="metric-label">{label}</span><strong><CountUp value={value}/></strong><small>GRID INCIDENT RECORDS</small></SpotlightCard>)}<SpotlightCard className="metric peak glass"><Globe2 size={17}/><span className="metric-label">PEAK YEAR</span><strong>2020</strong><small>HIGHEST INCIDENT VOLUME</small></SpotlightCard></section><section className="section-head" id="geography"><span>01 / OVERVIEW</span><h2>Operational picture</h2><p>Incident volume, casualty burden and global distribution.</p></section><DashboardFrame/><section className="footer-panel glass" id="tactics"><div><span className="label">SOURCE</span><strong>Global Terrorism Trends and Analysis Center</strong><p>Record of Incident Database (GRID). Original visualization generated from the supplied GRID snapshot.</p></div><a href="https://www.GTTAC.com" target="_blank" rel="noreferrer">GTTAC <ExternalLink size={13}/></a><a href="https://www.GRIDdata.com" target="_blank" rel="noreferrer">GRID <ExternalLink size={13}/></a></section></main>}
createRoot(document.getElementById('root')).render(<App/>);